//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translatables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translatables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVVMFramework.Translatables", typeof(Translatables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Chapters.
        /// </summary>
        public static string AddChapter {
            get {
                return ResourceManager.GetString("AddChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add chapter markers to video?.
        /// </summary>
        public static string AddChaptersMessage {
            get {
                return ResourceManager.GetString("AddChaptersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing video speed....
        /// </summary>
        public static string ChangingLabel {
            get {
                return ResourceManager.GetString("ChangingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again by importing the chapter marker file located at {0}..
        /// </summary>
        public static string ChapterAdderTryAgain {
            get {
                return ResourceManager.GetString("ChapterAdderTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter file should be in the following format:.
        /// </summary>
        public static string ChapterFileFormatMessage {
            get {
                return ResourceManager.GetString("ChapterFileFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters markers successfully added!.
        /// </summary>
        public static string ChaptersSuccessfullyAdded {
            get {
                return ResourceManager.GetString("ChaptersSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine sections into one video?.
        /// </summary>
        public static string CombineSectionsQuestion {
            get {
                return ResourceManager.GetString("CombineSectionsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining sections into one video....
        /// </summary>
        public static string CombiningSectionsIntoOneLabel {
            get {
                return ResourceManager.GetString("CombiningSectionsIntoOneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining sections....
        /// </summary>
        public static string CombiningSectionsLabel {
            get {
                return ResourceManager.GetString("CombiningSectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CompleteLabel {
            get {
                return ResourceManager.GetString("CompleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmationLabel {
            get {
                return ResourceManager.GetString("ConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter.
        /// </summary>
        public static string Converter {
            get {
                return ResourceManager.GetString("Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert video format.
        /// </summary>
        public static string ConvertFormatLabel {
            get {
                return ResourceManager.GetString("ConvertFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting video....
        /// </summary>
        public static string ConvertingLabel {
            get {
                return ResourceManager.GetString("ConvertingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string ConvertLabel {
            get {
                return ResourceManager.GetString("ConvertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this section?.
        /// </summary>
        public static string DeleteSectionConfirm {
            get {
                return ResourceManager.GetString("DeleteSectionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Downloader.
        /// </summary>
        public static string Downloader {
            get {
                return ResourceManager.GetString("Downloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be after the start time. Please select the start time again..
        /// </summary>
        public static string EndTimeAfterStartTime {
            get {
                return ResourceManager.GetString("EndTimeAfterStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string EndTimeLabel {
            get {
                return ResourceManager.GetString("EndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Please close and reopen the program. Check your task manager and make sure any remaining &quot;ffmpeg.exe&quot; tasks are ended..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        public static string FlipLabel {
            get {
                return ResourceManager.GetString("FlipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string FormatLabel {
            get {
                return ResourceManager.GetString("FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting metadata....
        /// </summary>
        public static string GettingMetadataMessage {
            get {
                return ResourceManager.GetString("GettingMetadataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Chapter File.
        /// </summary>
        public static string ImportLabel {
            get {
                return ResourceManager.GetString("ImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationLabel {
            get {
                return ResourceManager.GetString("InformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a title for every section. Click on the red sections to double check the title names..
        /// </summary>
        public static string InsufficientTitles {
            get {
                return ResourceManager.GetString("InsufficientTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to time.
        /// </summary>
        public static string JumpToTimeLabel {
            get {
                return ResourceManager.GetString("JumpToTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string MergeLabel {
            get {
                return ResourceManager.GetString("MergeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merger.
        /// </summary>
        public static string Merger {
            get {
                return ResourceManager.GetString("Merger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging videos....
        /// </summary>
        public static string MergingLabel {
            get {
                return ResourceManager.GetString("MergingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDownLabel {
            get {
                return ResourceManager.GetString("MoveDownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUpLabel {
            get {
                return ResourceManager.GetString("MoveUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected..
        /// </summary>
        public static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled..
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output folder.
        /// </summary>
        public static string OutputFolderLabel {
            get {
                return ResourceManager.GetString("OutputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format.
        /// </summary>
        public static string OutputFormatLabel {
            get {
                return ResourceManager.GetString("OutputFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output to a different format?.
        /// </summary>
        public static string OutputFormatQuestion {
            get {
                return ResourceManager.GetString("OutputFormatQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseLabel {
            get {
                return ResourceManager.GetString("PauseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayLabel {
            get {
                return ResourceManager.GetString("PlayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM usage exceeds {0}%..
        /// </summary>
        public static string RamUsageLabel {
            get {
                return ResourceManager.GetString("RamUsageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Size.
        /// </summary>
        public static string ReduceSize {
            get {
                return ResourceManager.GetString("ReduceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce video size.
        /// </summary>
        public static string ReduceVideoSizeLabel {
            get {
                return ResourceManager.GetString("ReduceVideoSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducing video size....
        /// </summary>
        public static string ReducingSizeLabel {
            get {
                return ResourceManager.GetString("ReducingSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Re-encoding is more time-consuming, but the start and end times will be more accurate and it will prevent any black frames at the beginning and end of the clips..
        /// </summary>
        public static string ReEncodeComment {
            get {
                return ResourceManager.GetString("ReEncodeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-encode video?*.
        /// </summary>
        public static string ReEncodeQuestion {
            get {
                return ResourceManager.GetString("ReEncodeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveLabel {
            get {
                return ResourceManager.GetString("RemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string ReverseLabel {
            get {
                return ResourceManager.GetString("ReverseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverser.
        /// </summary>
        public static string Reverser {
            get {
                return ResourceManager.GetString("Reverser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversing a video uses a lot of computer resources and can be time consuming. If you are going to reverse a video, make sure of the following:
        ///  1) It is best to not have other big programs running.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string ReverseVideoMessage {
            get {
                return ResourceManager.GetString("ReverseVideoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversing sections....
        /// </summary>
        public static string ReversingSectionsLabel {
            get {
                return ResourceManager.GetString("ReversingSectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string RotateLabel {
            get {
                return ResourceManager.GetString("RotateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back (5 sec.).
        /// </summary>
        public static string SeekBackLabel {
            get {
                return ResourceManager.GetString("SeekBackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward (5 sec.).
        /// </summary>
        public static string SeekForwardLabel {
            get {
                return ResourceManager.GetString("SeekForwardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select a file....
        /// </summary>
        public static string SelectFileLabel {
            get {
                return ResourceManager.GetString("SelectFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting metadata....
        /// </summary>
        public static string SettingMetadataMessage {
            get {
                return ResourceManager.GetString("SettingMetadataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Reducer.
        /// </summary>
        public static string SizeReducer {
            get {
                return ResourceManager.GetString("SizeReducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size successfully reduced!.
        /// </summary>
        public static string SizeSuccessfullyReduced {
            get {
                return ResourceManager.GetString("SizeSuccessfullyReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Speed.
        /// </summary>
        public static string SpeedChanger {
            get {
                return ResourceManager.GetString("SpeedChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string SplitLabel {
            get {
                return ResourceManager.GetString("SplitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter.
        /// </summary>
        public static string Splitter {
            get {
                return ResourceManager.GetString("Splitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting video....
        /// </summary>
        public static string SplittingLabel {
            get {
                return ResourceManager.GetString("SplittingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTimeLabel {
            get {
                return ResourceManager.GetString("StartTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopLabel {
            get {
                return ResourceManager.GetString("StopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimming video into sections....
        /// </summary>
        public static string TrimmingSectionsLabel {
            get {
                return ResourceManager.GetString("TrimmingSectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video {0} of {1}.
        /// </summary>
        public static string VideoCounterLabel {
            get {
                return ResourceManager.GetString("VideoCounterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Editor.
        /// </summary>
        public static string VideoEditor {
            get {
                return ResourceManager.GetString("VideoEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video speed.
        /// </summary>
        public static string VideoSpeedLabel {
            get {
                return ResourceManager.GetString("VideoSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video speed successfully changed!.
        /// </summary>
        public static string VideoSpeedSuccessfullyChanged {
            get {
                return ResourceManager.GetString("VideoSpeedSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video successfully converted!.
        /// </summary>
        public static string VideoSuccessfullyConverted {
            get {
                return ResourceManager.GetString("VideoSuccessfullyConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos successfully merged!.
        /// </summary>
        public static string VideoSuccessfullyMerged {
            get {
                return ResourceManager.GetString("VideoSuccessfullyMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video successfully reversed!.
        /// </summary>
        public static string VideoSuccessfullyReversed {
            get {
                return ResourceManager.GetString("VideoSuccessfullyReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video successfully split!.
        /// </summary>
        public static string VideoSuccessfullySplit {
            get {
                return ResourceManager.GetString("VideoSuccessfullySplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video file exceeds 1 minute. If you continue it is possible your computer will run out of memory during the process and freeze. Do you still want to continue?.
        /// </summary>
        public static string VideoTooBigMessage {
            get {
                return ResourceManager.GetString("VideoTooBigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningLabel {
            get {
                return ResourceManager.GetString("WarningLabel", resourceCulture);
            }
        }
    }
}
